spring:
  datasource:
    url: jdbc:h2:file:./data/webhookdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  generate-webhook-url: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"
  test-webhook-url: "https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA"
  regNo: "22BCE8554"
  name: "John Doe"
  email: "john@example.com"
